### ISSUE TITLE
Minor code style comments

### ISSUE THREAD

**Issue by alejandrogallo** [mishioo/tesliper#3]
I'd like to comment on two minor issues about the python style:

1. there is no code style I could find about specific contributing guidelines
   in terms of code quality and style, which due to the willingness
   to provide support and merge contributions is ok.
   However the code is extensively gradually typed,
   which begs the question what is the author's approach
   to typing.
   Doing `mypy tesliper` shows that it is not intended to
   be `mypy`ed.
2. there is the `black` style banner but I see no
   enforcement of the style in the CI or contributed notes
   about running the black code formatter on the code base
   upon submission, I might have missed it.
   It might be a good idea to add a code contribution
   guidelines to the README.
3. why 3 separated requirement files?
   I would tend to unify for ease of contribution
   specially if as in the ROADMAP stated the author
   is thinking of embedding some of `cclib`'s functionality.
   Please consider adding this to the `setup.py`
   file
   ```python
    extras_require=dict(
        # List additional groups of dependencies here (e.g. development
        # dependencies). You can install these using the following syntax,
        # for example:
        # $ pip install -e .[gui]
        # or
        # $ pip install -e .[dev]
        gui=[
            "matplotlib",
        ],
        dev=[
            "numpy",
            "openpyxl",
            "matplotlib",
            "black",
            "pre-commit",
            "flake8",
            "coverage",
            "pytest",
            "hypothesis",
            "isort",
            "pyinstaller",
            "twine",
            "sphinx",
            "sphinx-rtd-theme",
        ]
    ),
    ```
   and one can use them by doing
  `pip install .[dev]` for instance, also in the appveyor CI.
4. I am uncertain exactly when `tkinter` is packaged with python,
   in which OSes or distributions and in which installation methods.
   You inform the user that it is a dependency in the same sense
   that matplotlib is.
   However, in the case that the user has a pyhon3.6+ version
   not packaging tkinter the `gui` will not work, as it is not
   specified in the `setup.py` (correctly so in my opinion).
   Maybe it is a good idea to separate the tkinter dependcy notice
   and add a sentence informing the user that tkinter is packaged
   alongside most python distributions informing the user of this
   possibility in case of trouble.

**Comment by mishioo** [comment]
Re 1: integration of `mypy` is on my "to do if I got time" list. I started adding type hints to new and updated code some time ago, mostly having a documentation and better IDE experience in mind. Making it fully `mypy`able will probably still require quite a lot of work, unfortunately.

**Comment by mishioo** [comment]
Re 2: I've configured `black` in my local pre-commit hook and it was sufficient for me while I was the only contributor. Definitely right that running the formatter upon submission is a better option, I'll look into setting up a GitHub action.

**Comment by mishioo** [comment]
Re 3: I've used separate requirements files before I've added `setup.py` file and they just... stuck around. I'll move requirements to `setup.py` as you suggested.

**Comment by mishioo** [comment]
Re 4: As far as I know, Windows version always comes with `tkinter` and Linux sometimes requires installing it via a package manager (however, I used mostly Ubuntu). No idea about MacOS. The suggestion to separate the `tkinter` dependency notice, definitely sounds like a good idea, I'll do that.

**Comment by mishioo** [comment]
Re 1, 2: I've added information about type hints and code formatting in the "Participating in code" section of `READEME.md`.
Re 3: Requirements are now in `setup.py` file, `requirements.txt` files were removed.
Re 4: I've moved the `tkinter` dependency notice out of the list of requirements in the project's description.
