### ISSUE TITLE
Entry point suggestion for *nix users 

### ISSUE THREAD

**Issue by alejandrogallo** [mishioo/tesliper#4]
In terms of ergonomics, it is ok to tell the user to do

```
python -m tesliper.gui
```

I would suggest the author consider
adding this to the `setup.py` script

```
    ...
    entry_points={
        'console_scripts': [
            'tesliper-gui=tesliper.gui:run',
        ],
    },
    ...
```

which will generate add a `tesliper-gui` runnable script in the user's path.

Refer to [here](https://packaging.python.org/en/latest/specifications/entry-points/) for more information.

**Comment by mishioo** [comment]
Sure, great suggestion.
